### ISSUE TITLE
Bad Gateway Error with direct link

### ISSUE THREAD

**Issue by TheBig-O** [Flomp/wanderer#102]
Any time I use a direct link to a trail, I get an error saying "Bad Gateway."
For example, when paste `https://example.com/trail/view/vahveq98siviv66` into the address bar, I get the following in the logs:

```
[INFO] [03:15:00]: Starting auto-upload
[ERROR] [03:15:00]: Login failed. Unable to obtain cookie.
SvelteKitError: Not found: /trails/view/vahveq98siviv66
    at resolve2 (file:///app/build/server/index.js:4069:18)
    at resolve (file:///app/build/server/index.js:3901:34)
    at Object.handle (file:///app/build/server/chunks/hooks.server-49W1TjIe.js:59:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///app/build/server/index.js:3899:22)
    at async Array.ssr (file:///app/build/handler.js:1243:3) {
  status: 404,
  text: 'Not Found'
}
```

Any idea why it seems to be dumping the cookie. It's acting like I'm not logged in, but I'm definitely logged in and can pull up the trail through the menus.  I have no idea why the bad gateway error or what is going on.
Thanks for the help fixing this.

**Comment by Flomp** [comment]
That's strange. Does this also happen for you on the demo instance?
E.g. [https://demo.wanderer.to/trail/view/jmolew6qjtkmx5f](https://demo.wanderer.to/trail/view/jmolew6qjtkmx5f)

**Comment by TheBig-O** [comment]
So, I tried the link that you provided and it does come up without issue. This makes me think that it has something to do with the setup and reverse proxy I'm using. 
I'm using NGINX Proxy Manager with no unusual setup, locations, or otherwise.
Any thoughts? Below is my docker-compose.

```
version: "3"
x-common-env: &a1
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: Supersecretreallylongcode
services:
  search:
    container_name: wanderer-search
    image: flomp/wanderer-search
    environment:
      <<: *a1
      MEILI_NO_ANALYTICS: true
    ports:
      - 7777:7700
    networks:
      - wanderer
    volumes:
      - /<MyPath>/wanderer/data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  db:
    container_name: wanderer-db
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *a1
    ports:
      - 8090:8090
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - /<MyPath>/wanderer/data/pb_data:/pb_data
  web:
    container_name: wanderer-web
    image: flomp/wanderer-web
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      <<: *a1
      #      ORIGIN: http://localhost:3000
      #      ORIGIN: http://192.168.1.174:3332
      ORIGIN: https://trails.example\domain.org
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: true
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER: null
      UPLOAD_PASSWORD: null
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
    volumes:
      - /<MyPath>/wanderer/data/uploads:/app/uploads
    ports:
      - 3332:3000
    networks:
      - wanderer
    restart: unless-stopped
  # valhalla:
  #   image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - /<MyPath>/wanderer/data/valhalla:/custom_files
  #   environment:
  #     - tile_urls=https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf
  #     - use_tiles_ignore_pbf=True
  #     - force_rebuild=False
  #     - force_rebuild_elevation=False
  #     - build_elevation=True
  #     - build_admins=True
  #     - build_time_zones=True

networks:
  wanderer:
    driver: bridge
```
