### ISSUE TITLE
Pocketbase returns SQLITE_BUSY

### ISSUE THREAD

**Issue by signed-log** [Flomp/wanderer#169]
On a clean install of wanderer v14.0 with the following docker compose

```yaml
x-common-env: &cenv
  MEILI_URL: http://wanderer-search:7700
  MEILI_MASTER_KEY: <REDACTED>

services:
  wanderer-search:
    container_name: wanderer-search
    image: getmeili/meilisearch:v1.12.8
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    networks:
      - wanderer
    volumes:
      - ./wanderer/data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  wanderer-db:
    container_name: wanderer-db
    #image: flomp/wanderer-db
    build: ./wanderer/docker
    depends_on:
      wanderer-search:
        condition: service_healthy
    environment:
      <<: *cenv
    networks:
      - wanderer
  restart: unless-stopped
    volumes:
      - ./wanderer/data/pb_data:/pb_data
  wanderer-web:
    container_name: wanderer-web
    image: flomp/wanderer-web:v0.14.0
    depends_on:
      wanderer-search:
        condition: service_healthy
      wanderer-db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: https://wander.example.com
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://wanderer-db:8090
      PUBLIC_DISABLE_SIGNUP: true
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER:
      UPLOAD_PASSWORD:
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
    volumes:
      - ./wanderer/data/uploads:/app/uploads
    networks:
      - web
      - wanderer
networks:
  web:
    external: true
  wanderer:
```

On `docker compose up -d` it waits a while before crashing with `SQLITE_BUSY`
```
wanderer-db  | [9732.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
wanderer-db  | [9632.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
wanderer-db  | [9527.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
wanderer-db  | [9214.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
wanderer-db  | [0.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
wanderer-db  | [9430.00ms] SELECT {{_collections}}.* FROM `_collections`
wanderer-db  | [9604.00ms] SELECT {{_collections}}.* FROM `_collections`
wanderer-db  | [9733.00ms] SELECT {{_collections}}.* FROM `_collections`
wanderer-db  | [9731.00ms] SELECT {{_collections}}.* FROM `_collections`
wanderer-db  | [0.00ms] SELECT {{_collections}}.* FROM `_collections`
wanderer-db  | [9934.00ms] CREATE TABLE IF NOT EXISTS `_migrations` (file VARCHAR(255) PRIMARY KEY NOT NULL, applied INTEGER NOT NULL)
wanderer-db  | Error: database is locked (5) (SQLITE_BUSY)
wanderer-db exited with code 0
wanderer-db  | [9937.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
```

Info :

The following dockerfile was used to display SQL log

```dockerfile
FROM flomp/wanderer-db:v0.14.0
ENTRYPOINT ["/pocketbase", "serve", "--http=0.0.0.0:8090", "--dev", "--dir=/pb_data"]
```

The frontend reports connection refused after the SQLITE_BUSY occurs in the DB and no other log occur
