### ISSUE TITLE
Suggestions for adding healthchecks to wanderer and pocketbase containers?

### ISSUE THREAD

**Issue by ovizii** [Flomp/wanderer#21]
I assume something simple like this could work or are there better endpoints / APIs to check?

Use this with port 3000 and another one for port 8090?
```
    healthcheck:
      test: curl -ILfSs http://localhost:3000 > /dev/null || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
```

And looking at the sample healthcheck for meilisearch:
```
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 30s
      retries: 10
      start_period: 30s
      timeout: 10s
```
