### ISSUE TITLE
JS uncaught error: "Style is not done loading." from MapLibre GL JS

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#286]
I've this installation:
```
x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}

networks:
  wanderer:
  proxy:
    external: true

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_FOLDER}/db
  search:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INSTANCE_FOLDER}/search
  uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_FOLDER}/uploads
  valhalla:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INSTANCE_FOLDER}/valhalla

services:
  search:
    #container_name: wanderer-search
    image: getmeili/meilisearch:v1.11.3
    user: "1000:1000"
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    #ports:
    #  - 7700:7700
    networks:
      - wanderer
    volumes:
      - search:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s

  db:
    #container_name: wanderer-db
    image: flomp/wanderer-db
    user: "1000:1000"
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
      POCKETBASE_ENCRYPTION_KEY: ${POCKETBASE_ENCRYPTION_KEY}
      POCKETBASE_CRON_SYNC_SCHEDULE: 45 21 * * *
      POCKETBASE_SUPERUSER_USERNAME: ${POCKETBASE_SUPERUSER_USERNAME}
      POCKETBASE_SUPERUSER_PASSWORD: ${POCKETBASE_SUPERUSER_PASSWORD}
    #ports:
    #  - "8090:8090"
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - db:/pb_data
      - ${DATA_FOLDER}/migrations/1745849033_create_superuser.go:/migrations/1745849033_create_superuser.go

  web:
    #container_name: wanderer-web
    image: flomp/wanderer-web
    user: "1000:1000"
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: https://${HTTP_PRODUCTION_DOMAIN}
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: true
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER:
      UPLOAD_PASSWORD:
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
      #PUBLIC_VALHALLA_URL: http://valhalla:8002/
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
    volumes:
      - uploads:/app/uploads
    #ports:
    #  - "3000:3000"
    networks:
      - wanderer
      - proxy
    restart: unless-stopped
    labels:
      # common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # production / staging
      - 'traefik.http.routers.${APP_NAME}-https.rule=Host(`${HTTP_PRODUCTION_DOMAIN}`)'
      - 'traefik.http.routers.${APP_NAME}-https.entrypoints=web-secured'
      - 'traefik.http.routers.${APP_NAME}-https.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.${APP_NAME}-https.service=${APP_NAME}-http'
      - 'traefik.http.services.${APP_NAME}-http.loadbalancer.server.port=3000'
      - 'traefik.http.services.${APP_NAME}-http.loadbalancer.server.scheme=http'

#  valhalla:
#     image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
#     ports:
#       - "8002:8002"
#     networks:
#       - wanderer
#     volumes:
#       - valhalla:/custom_files
#     environment:
#       - tile_urls=https://download.geofabrik.de/europe/germany-latest.osm.pbf https://download.geofabrik.de/europe/france-latest.osm.pbf
#       - use_tiles_ignore_pbf=True
#       - force_rebuild=False
#       - force_rebuild_elevation=False
#       - build_elevation=True
#       - build_admins=True
#       - build_time_zones=True
```

Most is running well, but on the /map route i get this error:
```
Sh27gn0J.js:1 Uncaught Error: Style is not done loading.
    at js._checkLoaded (CDOosi66.js:5:368740)
    at js.addSource (CDOosi66.js:5:373109)
    at k.Map.addSource (CDOosi66.js:580:203436)
    at Qe (DmfNIohn.js:2:22463)
    at ye (DmfNIohn.js:2:19995)
    at DmfNIohn.js:2:19058
    at zn (Sh27gn0J.js:1:11771)
    at DmfNIohn.js:2:19037
    at rn (Sh27gn0J.js:1:9083)
    at Tt (Sh27gn0J.js:1:9864)
```
The map is zoomed to 1m and black. Once i scroll out i get the map tiles rendered. Once i change the route the same error happens again.
