### ISSUE TITLE
wanderer-web: Login failed. Unable to obtain cookie.

### ISSUE THREAD

**Issue by update-freak** [Flomp/wanderer#298]
In the wanderer-web docker log I get always:

```
[ERROR] [15:15:02]: Login failed. Unable to obtain cookie.
[INFO] [15:30:00]: Starting auto-upload
[ERROR] [15:30:00]: Login failed. Unable to obtain cookie.
[INFO] [15:45:00]: Starting auto-upload
```

Not sure what is the root cause.

Here is my docker compose file:
```
x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: beispielkey

services:
  search:
    container_name: wanderer-search
    image: getmeili/meilisearch:v1.11.3
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    ports:
      - 7700:7700
    networks:
      - wanderer
    volumes:
      - /volume1/docker/wanderer/meili_data:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  db:
    container_name: wanderer-db
    image: flomp/wanderer-db:latest
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
      POCKETBASE_ENCRYPTION_KEY: irgendeinkey
    ports:
      - "8090:8090"
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - /volume1/docker/wanderer/pb_data:/pb_data
  web:
    container_name: wanderer-web
    image: flomp/wanderer-web:latest
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: https://wanderer.beispiel.dynv6.net
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: true
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER:
      UPLOAD_PASSWORD:
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
    volumes:
      - /volume1/docker/wanderer/uploads:/app/uploads
    ports:
      - "1048:3000"
    networks:
      - wanderer
    restart: unless-stopped

networks:
  wanderer:
    driver: bridge
```
