### ISSUE TITLE
Error Calculating Route

### ISSUE THREAD

**Issue by bauerbyter** [Flomp/wanderer#366]
Hey,

first: I love wanderer, thanks!
Everything works as expected except of the routing system. Tried it with selfhosted valhalla, but same problem. 
I get the error message (this could need some improvement, error code?) Error Caluclating Route.
In the logs of the docker container there is nothing, but the browser has this error: 

```
  XHRPOST
  https://wanderer.<removed>.casa/api/v1/valhalla/route
  [HTTP/2 500  63ms]
  
  	
  POST
  	https://wanderer.<removed>.casa/api/v1/valhalla/route
  Status
  500
  VersionHTTP/2
  Transferred1.46 kB (2 B size)
  Referrer Policystrict-origin-when-cross-origin
  Request PriorityHighest
  DNS ResolutionSystem

    	
    alt-svc
    	h3=":443"; ma=2592000
    content-length
    	2
    content-type
    	application/json
    date
    	Sun, 29 Jun 2025 12:55:11 GMT
    set-cookie
    	pb_auth=%7B%22token<removed>; Path=/; Expires=Sun, 13 Jul 2025 12:55:11 GMT; Secure; SameSite=Lax
    via
    	1.1 Caddy
    X-Firefox-Spdy
    	h2
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br, zstd
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	275
    Content-Type
    	text/plain;charset=UTF-8
    Cookie
    	pb_auth=<removed>
    Host
    	wanderer.<removed>.casa
    Origin
    	https://wanderer.bauerbyter.casa
    Priority
    	u=0
    Referer
    	https://wanderer.<removed>.casa/trail/edit/new
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0
```

Can someone help me to fix this? Thanks :)

**Comment by memthw** [comment]
It is happening to me as well with or without reverse proxy and using http with IP address and port (ORIGIN variable is set correctly) as well.

**Comment by Flomp** [comment]
This is hard to pinpoint without further information:
1. Which version of wanderer are you on? The URL of the public valhalla instance changed recently.
2. Can you try to calculate the same route on the demo instance: https://demo.wanderer.to/trail/edit/new
3. Can you try to calculate the same route on the valhalla website: https://valhalla.openstreetmap.de/

Please also try playing around with the routing settings in both cases. The error usually indicates that valhalla cannot find a route between the two points you specified.

**Comment by bauerbyter** [comment]
Hey,
1.  V0.17.1
2. works totally fine
3. also

No routes work in my instance... totally easy ones like 100m apart dont work.

Maybe my docker compose helps:

```

x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: <removed>

services:
  search:
    container_name: wanderer-search
    image: getmeili/meilisearch:v1.11.3
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    ports:
      - 7700:7700
    networks:
      - wanderer
    volumes:
      - ./data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  db:
    container_name: wanderer-db
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
      POCKETBASE_ENCRYPTION_KEY: <removed>
      ORIGIN: https://wanderer.<removed>.casa
    ports:
      - "8095:8090"
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - ./data/pb_data:/pb_data
  web:
    container_name: wanderer-web
    image: flomp/wanderer-web
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: https://wanderer.<removed>.casa
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: false
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER:
      UPLOAD_PASSWORD:
      PUBLIC_VALHALLA_URL: https://valhalla.openstreetmap.de
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
    volumes:
      - ./data/uploads:/app/uploads
    ports:
      - "3032:3000"
    labels:
      caddy: wanderer.<removed>.casa 
      caddy.reverse_proxy: "{{upstreams 3000}}" 
    networks:
      - wanderer
      - caddy
    restart: unless-stopped

  # valhalla:
  #   image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./data/valhalla:/custom_files
  #   environment:
  #     - tile_urls=https://download.geofabrik.de/europe/germany-latest.osm.pbf
  #     - use_tiles_ignore_pbf=True
  #     - force_rebuild=False
  #     - force_rebuild_elevation=False
  #     - build_elevation=True
  #     - build_admins=True
  #     - build_time_zones=True
  #   networks:
  #    - wanderer

networks:
  wanderer:
    driver: bridge
  caddy:
    external: true
```
